/*
 * Adobe Experience Manager (AEM) API
 * Swagger AEM is an OpenAPI specification for Adobe Experience Manager (AEM) API
 *
 * OpenAPI spec version: 3.7.1-pre.0
 * Contact: opensource@shinesolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model.adobeModel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.adobeModel.BundleDataProp;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * BundleData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-15T21:05:42.103338900+03:00[Europe/Moscow]")
public class BundleData {
  @SerializedName("category")
  private String category = null;

  @SerializedName("fragment")
  private Boolean fragment = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("props")
  private List<BundleDataProp> props = null;

  @SerializedName("state")
  private String state = null;

  @SerializedName("stateRaw")
  private Integer stateRaw = null;

  @SerializedName("symbolicName")
  private String symbolicName = null;

  @SerializedName("version")
  private String version = null;

  public BundleData category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Bundle category
   * @return category
  **/
  @Schema(description = "Bundle category")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public BundleData fragment(Boolean fragment) {
    this.fragment = fragment;
    return this;
  }

   /**
   * Is bundle a fragment
   * @return fragment
  **/
  @Schema(description = "Is bundle a fragment")
  public Boolean isFragment() {
    return fragment;
  }

  public void setFragment(Boolean fragment) {
    this.fragment = fragment;
  }

  public BundleData id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Bundle ID
   * @return id
  **/
  @Schema(description = "Bundle ID")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public BundleData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Bundle name
   * @return name
  **/
  @Schema(description = "Bundle name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BundleData props(List<BundleDataProp> props) {
    this.props = props;
    return this;
  }

  public BundleData addPropsItem(BundleDataProp propsItem) {
    if (this.props == null) {
      this.props = new ArrayList<BundleDataProp>();
    }
    this.props.add(propsItem);
    return this;
  }

   /**
   * Get props
   * @return props
  **/
  @Schema(description = "")
  public List<BundleDataProp> getProps() {
    return props;
  }

  public void setProps(List<BundleDataProp> props) {
    this.props = props;
  }

  public BundleData state(String state) {
    this.state = state;
    return this;
  }

   /**
   * Bundle state value
   * @return state
  **/
  @Schema(description = "Bundle state value")
  public String getState() {
    return state;
  }

  public void setState(String state) {
    this.state = state;
  }

  public BundleData stateRaw(Integer stateRaw) {
    this.stateRaw = stateRaw;
    return this;
  }

   /**
   * Numeric raw bundle state value
   * @return stateRaw
  **/
  @Schema(description = "Numeric raw bundle state value")
  public Integer getStateRaw() {
    return stateRaw;
  }

  public void setStateRaw(Integer stateRaw) {
    this.stateRaw = stateRaw;
  }

  public BundleData symbolicName(String symbolicName) {
    this.symbolicName = symbolicName;
    return this;
  }

   /**
   * Bundle symbolic name
   * @return symbolicName
  **/
  @Schema(description = "Bundle symbolic name")
  public String getSymbolicName() {
    return symbolicName;
  }

  public void setSymbolicName(String symbolicName) {
    this.symbolicName = symbolicName;
  }

  public BundleData version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Bundle version
   * @return version
  **/
  @Schema(description = "Bundle version")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BundleData bundleData = (BundleData) o;
    return Objects.equals(this.category, bundleData.category) &&
        Objects.equals(this.fragment, bundleData.fragment) &&
        Objects.equals(this.id, bundleData.id) &&
        Objects.equals(this.name, bundleData.name) &&
        Objects.equals(this.props, bundleData.props) &&
        Objects.equals(this.state, bundleData.state) &&
        Objects.equals(this.stateRaw, bundleData.stateRaw) &&
        Objects.equals(this.symbolicName, bundleData.symbolicName) &&
        Objects.equals(this.version, bundleData.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(category, fragment, id, name, props, state, stateRaw, symbolicName, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BundleData {\n");
    
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    fragment: ").append(toIndentedString(fragment)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    props: ").append(toIndentedString(props)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    stateRaw: ").append(toIndentedString(stateRaw)).append("\n");
    sb.append("    symbolicName: ").append(toIndentedString(symbolicName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
