/*
 * Adobe Experience Manager (AEM) API
 * Swagger AEM is an OpenAPI specification for Adobe Experience Manager (AEM) API
 *
 * OpenAPI spec version: 3.7.1-pre.0
 * Contact: opensource@shinesolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model.adobeModel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.File;
import java.io.IOException;
/**
 * IntermediatePathAuthorizableIdKsHtmlBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-15T21:05:42.103338900+03:00[Europe/Moscow]")
public class IntermediatePathAuthorizableIdKsHtmlBody {
  @SerializedName("cert-chain")
  private File certChain = null;

  @SerializedName("keyStore")
  private File keyStore = null;

  @SerializedName("pk")
  private File pk = null;

  public IntermediatePathAuthorizableIdKsHtmlBody certChain(File certChain) {
    this.certChain = certChain;
    return this;
  }

   /**
   * Get certChain
   * @return certChain
  **/
  @Schema(description = "")
  public File getCertChain() {
    return certChain;
  }

  public void setCertChain(File certChain) {
    this.certChain = certChain;
  }

  public IntermediatePathAuthorizableIdKsHtmlBody keyStore(File keyStore) {
    this.keyStore = keyStore;
    return this;
  }

   /**
   * Get keyStore
   * @return keyStore
  **/
  @Schema(description = "")
  public File getKeyStore() {
    return keyStore;
  }

  public void setKeyStore(File keyStore) {
    this.keyStore = keyStore;
  }

  public IntermediatePathAuthorizableIdKsHtmlBody pk(File pk) {
    this.pk = pk;
    return this;
  }

   /**
   * Get pk
   * @return pk
  **/
  @Schema(description = "")
  public File getPk() {
    return pk;
  }

  public void setPk(File pk) {
    this.pk = pk;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntermediatePathAuthorizableIdKsHtmlBody intermediatePathAuthorizableIdKsHtmlBody = (IntermediatePathAuthorizableIdKsHtmlBody) o;
    return Objects.equals(this.certChain, intermediatePathAuthorizableIdKsHtmlBody.certChain) &&
        Objects.equals(this.keyStore, intermediatePathAuthorizableIdKsHtmlBody.keyStore) &&
        Objects.equals(this.pk, intermediatePathAuthorizableIdKsHtmlBody.pk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Objects.hashCode(certChain), Objects.hashCode(keyStore), Objects.hashCode(pk));
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntermediatePathAuthorizableIdKsHtmlBody {\n");
    
    sb.append("    certChain: ").append(toIndentedString(certChain)).append("\n");
    sb.append("    keyStore: ").append(toIndentedString(keyStore)).append("\n");
    sb.append("    pk: ").append(toIndentedString(pk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
