/*
 * Adobe Experience Manager (AEM) API
 * Swagger AEM is an OpenAPI specification for Adobe Experience Manager (AEM) API
 *
 * OpenAPI spec version: 3.7.1-pre.0
 * Contact: opensource@shinesolutions.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model.adobeModel;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.adobeModel.KeystoreChainItems;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * KeystoreItems
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-15T21:05:42.103338900+03:00[Europe/Moscow]")
public class KeystoreItems {
  @SerializedName("algorithm")
  private String algorithm = null;

  @SerializedName("alias")
  private String alias = null;

  @SerializedName("chain")
  private List<KeystoreChainItems> chain = null;

  @SerializedName("entryType")
  private String entryType = null;

  @SerializedName("format")
  private String format = null;

  public KeystoreItems algorithm(String algorithm) {
    this.algorithm = algorithm;
    return this;
  }

   /**
   * e.g. \&quot;RSA\&quot;
   * @return algorithm
  **/
  @Schema(description = "e.g. \"RSA\"")
  public String getAlgorithm() {
    return algorithm;
  }

  public void setAlgorithm(String algorithm) {
    this.algorithm = algorithm;
  }

  public KeystoreItems alias(String alias) {
    this.alias = alias;
    return this;
  }

   /**
   * Keystore alias name
   * @return alias
  **/
  @Schema(description = "Keystore alias name")
  public String getAlias() {
    return alias;
  }

  public void setAlias(String alias) {
    this.alias = alias;
  }

  public KeystoreItems chain(List<KeystoreChainItems> chain) {
    this.chain = chain;
    return this;
  }

  public KeystoreItems addChainItem(KeystoreChainItems chainItem) {
    if (this.chain == null) {
      this.chain = new ArrayList<KeystoreChainItems>();
    }
    this.chain.add(chainItem);
    return this;
  }

   /**
   * Get chain
   * @return chain
  **/
  @Schema(description = "")
  public List<KeystoreChainItems> getChain() {
    return chain;
  }

  public void setChain(List<KeystoreChainItems> chain) {
    this.chain = chain;
  }

  public KeystoreItems entryType(String entryType) {
    this.entryType = entryType;
    return this;
  }

   /**
   * e.g. \&quot;privateKey\&quot;
   * @return entryType
  **/
  @Schema(description = "e.g. \"privateKey\"")
  public String getEntryType() {
    return entryType;
  }

  public void setEntryType(String entryType) {
    this.entryType = entryType;
  }

  public KeystoreItems format(String format) {
    this.format = format;
    return this;
  }

   /**
   * e.g. \&quot;PKCS#8\&quot;
   * @return format
  **/
  @Schema(description = "e.g. \"PKCS#8\"")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeystoreItems keystoreItems = (KeystoreItems) o;
    return Objects.equals(this.algorithm, keystoreItems.algorithm) &&
        Objects.equals(this.alias, keystoreItems.alias) &&
        Objects.equals(this.chain, keystoreItems.chain) &&
        Objects.equals(this.entryType, keystoreItems.entryType) &&
        Objects.equals(this.format, keystoreItems.format);
  }

  @Override
  public int hashCode() {
    return Objects.hash(algorithm, alias, chain, entryType, format);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeystoreItems {\n");
    
    sb.append("    algorithm: ").append(toIndentedString(algorithm)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    chain: ").append(toIndentedString(chain)).append("\n");
    sb.append("    entryType: ").append(toIndentedString(entryType)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
